apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: logpull
  labels:
    name: logpull
spec:
  replicas: 1
  selector:
    matchLabels:
      name: logpull
  template:
    metadata:
      labels:
        name: logpull
        routable: "true"
      annotations:
        publicHosts: "shipyard.e2e.apigee.net"
        publicPaths: "8000:/logs"
        privateHosts: "shipyard.e2e.apigee.net"
        privatePaths: "8000:/logs"
    spec:
      containers:
      - image: thirtyx/logpull:dev
        imagePullPolicy: Always
        name: logpull
        env:
        - name: PORT
          value: "8000"
        - name: AUTH_API_HOST
          value: "api.e2e.apigee.net"
        - name: ELASTIC_SEARCH_HOST
          valueFrom:
            secretKeyRef:
              name: elastic-search-loc
              key: host
        - name: ELASTIC_SEARCH_PORT
          valueFrom:
            secretKeyRef:
              name: elastic-search-loc
              key: port
